services:
  ubuntu-c:
    container_name: ubuntu-c
    hostname: ubuntu-c
    build:
      context: ./ubuntu-c
      target: final
    depends_on:
    - ubuntu-t1
    tty: true

  ubuntu-t1:
    container_name: ubuntu-t1
    hostname: ubuntu-t1
    build: ./ubuntu-t1
    ports:
    - 2222:22
    - 8080:80
    tty: true